### ISSUE TITLE
Error when aligning shapes in slide master view

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1023]
System.NullReferenceException
Object reference not set to an instance of an object.
Stack Trace:
   at PowerPointLabs.PositionsLab.PositionsPaneWpf.DuplicateShapes(ShapeRange range)
   at PowerPointLabs.PositionsLab.PositionsPaneWpf.ExecutePositionsAction(Action`3 positionsAction, Single dimension1, Single dimension2, Boolean isPreview)

**Comment by fionachang** [comment]
This exception occurs for features that access the current slide in slide master view.

When getting the current slide in slide master view, `Globals.ThisAddIn.Application.ActiveWindow.View.Slide` returns a `master` object instead of a `slide` object. `PowerPointCurrentPresentationInfo.CurrentSlide` only handles `slide` objects so it returns `null` in slide master view.

By using a `dynamic` object, methods such as `Shapes.AddShape` and `Shapes.Paste` works for both `master` and `slide` objects. However, some methods only work for `slide` objects, for example, `Duplicate` and `Export`.

[https://social.msdn.microsoft.com/Forums/office/en-US/2c0c426c-2c12-49f8-a4d6-76e25cfc1eab/get-active-slide-in-slide-master-view-powerpoint-20072010?forum=officegeneral](url)

**Comment by Dawnlord** [comment]
New bugs met:

System.Runtime.InteropServices.COMException
View (unknown member) : Invalid request.  This view type does not support this action.
Stack Trace:
   在 Microsoft.Office.Interop.PowerPoint.View.GotoSlide(Int32 Index)
   在 PowerPointLabs.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AutoZoom.cs:行号 100

**Comment by Dawnlord** [comment]
Stack Trace:
   在 Microsoft.Office.Interop.PowerPoint.View.GotoSlide(Int32 Index)
   在 PowerPointLabs.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AutoZoom.cs:行号 110
   在 PowerPointLabs.AgendaLab.AgendaLabMain.GenerateVisualAgendaSlideZoomIn(PowerPointSlide slide, Shape zoomInShape) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AgendaLab\AgendaLabSyncFunctions.cs:行号 206
   在 PowerPointLabs.AgendaLab.AgendaLabMain.<>c.<.cctor>b__120_3(PowerPointSlide refSlide, List`1 sections, AgendaSection currentSection, List`1 deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide targetSlide) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AgendaLab\AgendaLabSyncFunctions.cs:行号 140
   在 PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate template, TemplateIndexTable templateTable, PowerPointSlide refSlide, List`1 sections, List`1 deletedShapeNames, AgendaSection currentSection) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AgendaLab\AgendaLabTemplateSyncLogic.cs:行号 260
   在 PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker slideTracker, PowerPointSlide refSlide, Func`1 generateTemplate) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AgendaLab\AgendaLabTemplateSyncLogic.cs:行号 37
   在 PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\AgendaLab\AgendaLabMain.cs:行号 135
   在 PowerPointLabs.Ribbon1.VisualAgendaClick(IRibbonControl control) 位置 D:\PPtLab\PowerPointLabs\PowerPointLabs\PowerPointLabs\Ribbon1.cs:行号 2334

**Comment by Dawnlord** [comment]
The problem is when using other master views, the program can automatically jump to `normal view` and jump back after generating agenda, but only when using `slide master view`, the program won't jump out of this view type. 

I am still try how to make the program jump to `normal view` even through in `slide master view`.

**Comment by Dawnlord** [comment]
When using `slide master view`, the view type returned is `ppViewNormal`. Therefore, it will make this bug.
