### ISSUE TITLE
FT_ShapesLabTest failing on ppt 2010

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1128]
**Error Message:**

Test Name:	FT_ShapesLabTest
Test FullName:	Test.FunctionalTest.ShapesLabTest.FT_ShapesLabTest
Test Source:	C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ShapesLabTest.cs : line 30
Test Outcome:	Failed
Test Duration:	0:00:07.8759228

Result StackTrace:	
Server stack trace: 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.RetrieveShapeGalleryFile() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 675
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.Close() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 177
   at PowerPointLabs.CustomShapePane.ImportShapes(String importFilePath, Boolean fromLibrary) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\CustomShapePane.cs:line 760
   at PowerPointLabs.CustomShapePane.ImportLibrary(String pathToLibrary) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\CustomShapePane.cs:line 1548
   at PowerPointLabs.FunctionalTestInterface.Impl.Controller.ShapesLabController.ImportLibrary(String pathToLibrary) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\FunctionalTestInterface.Impl\Controller\ShapesLabController.cs:line 55
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at TestInterface.IShapesLabController.ImportLibrary(String pathToLibrary)
   at Test.FunctionalTest.ShapesLabTest.TestImportLibraryAndShape(IShapesLabController shapesLab) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ShapesLabTest.cs:line 41
   at Test.FunctionalTest.ShapesLabTest.FT_ShapesLabTest() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\ShapesLabTest.cs:line 36
Result Message:	
Test method Test.FunctionalTest.ShapesLabTest.FT_ShapesLabTest threw exception: 
System.IO.IOException: The process cannot access the file because it is being used by another process.

**Comment by IanTeo** [comment]
Apparently, this test is failing on my machine but passes on the lab PC. I think it may have to do with the order of tests execution. More investigation is needed

**Comment by IanTeo** [comment]
similiarly for #1130

**Comment by YuPeiHenry** [comment]
@IanTeo I cannot replicate failing for this FT on my PPT2010. If you wish to pursue the matter, please reopen the issue.
