### ISSUE TITLE
FT_HighlightBulletsTest failing on ppt 2010

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1129]
**Error Message:**

Test Name:	FT_HighlightBulletsTest
Test FullName:	Test.FunctionalTest.HighlightBulletsTest.FT_HighlightBulletsTest
Test Source:	C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\HighlightBulletsTest.cs : line 17
Test Outcome:	Failed
Test Duration:	0:00:04.604541

Result StackTrace:	
at Test.Util.SlideUtil.IsSameAnimations(Slide expSlide, Slide actualSlide) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\Util\SlideUtil.cs:line 81
   at Test.FunctionalTest.HighlightBulletsTest.AssertIsSame(Int32 actualSlideIndex, Int32 expectedSlideIndex) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\HighlightBulletsTest.cs:line 121
   at Test.FunctionalTest.HighlightBulletsTest.TestHighlightPoints_SelectEndOfText() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\HighlightBulletsTest.cs:line 52
   at Test.FunctionalTest.HighlightBulletsTest.FT_HighlightBulletsTest() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\HighlightBulletsTest.cs:line 22
Result Message:	Assert.AreEqual failed. Expected:<2>. Actual:<14>. Different animation sequence count.

**Comment by leeyh20** [comment]
Worked for me on ppt 2010.

**Comment by YuPeiHenry** [comment]
Worked for me on ppt2010 as well, closing the issue.
