### ISSUE TITLE
FT_AgendaLabBeamSyncTest2 failing on ppt 2010

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1130]
**Error Message:**

Test Name:	FT_AgendaLabBeamSyncTest2
Test FullName:	Test.FunctionalTest.AgendaLabBeamSyncTest.FT_AgendaLabBeamSyncTest2
Test Source:	C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabBeamSyncTest.cs : line 28
Test Outcome:	Failed
Test Duration:	0:00:03.2144003

Result StackTrace:	
Server stack trace: 
   at Microsoft.Office.Interop.PowerPoint.Shape.get_Name()
   at PowerPointLabs.FunctionalTestInterface.Impl.PowerPointOperations.<>c__DisplayClass24_1.<RecursiveGetShapeWithPrefix>b__0(Shape shape) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\FunctionalTestInterface.Impl\PowerPointOperations.cs:line 226
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PowerPointLabs.FunctionalTestInterface.Impl.PowerPointOperations.RecursiveGetShapeWithPrefix(String[] prefixes) in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\FunctionalTestInterface.Impl\PowerPointOperations.cs:line 226
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at TestInterface.IPowerPointOperations.RecursiveGetShapeWithPrefix(String[] prefixes)
   at Test.FunctionalTest.AgendaLabBeamSyncTest.NoBeamTextUnsuccessful() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabBeamSyncTest.cs:line 100
   at Test.FunctionalTest.AgendaLabBeamSyncTest.FT_AgendaLabBeamSyncTest2() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabBeamSyncTest.cs:line 29
Result Message:	
Test method Test.FunctionalTest.AgendaLabBeamSyncTest.FT_AgendaLabBeamSyncTest2 threw exception: 
System.Runtime.InteropServices.COMException: Shape (unknown member) : Object does not exist.

**Comment by YuPeiHenry** [comment]
@IanTeo I cannot replicate failing for this FT on my PPT2010. If you wish to pursue the matter, please reopen the issue.
