### ISSUE TITLE
FT_AgendaLabTestSyncTest failing on ppt 2010

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1131]
This one is quite weird. The error message is very similar to the error message you would get before the manual fix.
**Error Message:**

Test Name:	FT_AgendaLabTextSyncTest
Test FullName:	Test.FunctionalTest.AgendaLabTextSyncTest.FT_AgendaLabTextSyncTest
Test Source:	C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabTextSyncTest.cs : line 17
Test Outcome:	Failed
Test Duration:	0:00:07.7593538

Result StackTrace:
Server stack trace: 
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.MarshalByRefObject.IsInstanceOfType(Type T)
   at System.Runtime.Remoting.DynamicTypeInfo.CanCastTo(Type castType, Object o)
   at System.Runtime.Remoting.Proxies.RemotingProxy.CanCastTo(Type castType, Object o)
   at System.Runtime.Remoting.RemotingServices.CheckCast(RealProxy rp, RuntimeType castType)
   at System.RuntimeTypeHandle.IsInstanceOfType(RuntimeType type, Object o)
   at System.RuntimeType.IsInstanceOfType(Object o)
   at System.Runtime.Remoting.Proxies.RealProxy.ValidateReturnArg(Object arg, Type paramType)
   at System.Runtime.Remoting.Proxies.RealProxy.PropagateOutParameters(IMessage msg, Object[] outArgs, Object returnValue)
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Office.Core.TextRange2.get_Paragraphs(Int32 Start, Int32 Length)
   at Test.FunctionalTest.AgendaLabTextSyncTest.HideUnvisitedSyncSuccessful() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabTextSyncTest.cs:line 32
   at Test.FunctionalTest.AgendaLabTextSyncTest.FT_AgendaLabTextSyncTest() in C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\Test\FunctionalTest\AgendaLabTextSyncTest.cs:line 18
Result Message:	
Test method Test.FunctionalTest.AgendaLabTextSyncTest.FT_AgendaLabTextSyncTest threw exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.=== Pre-bind state information ===
LOG: DisplayName = office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Ian/Desktop/PowerPointLabs/PowerPointLabs/PowerPointLabs/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Ian\Desktop\PowerPointLabs\PowerPointLabs\PowerPointLabs\bin\Debug\PowerPointLabs.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

**Comment by YuPeiHenry** [comment]
@IanTeo I cannot replicate failing for this FT on my PPT2010. If you wish to pursue the matter, please reopen the issue.
