### ISSUE TITLE
System.ArgumentException: The specified file wasn't found.

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#1299]
Cause: the target image object is corrupted somehow that its FullSizeImageFile and ImageFile are null or incorrect (?).

https://github.com/PowerPointLabs/PowerPointLabs/blob/e6f28d789ee9b5700a6bae4d6d9c13d42f3d950b/PowerPointLabs/PowerPointLabs/PictureSlidesLab/Service/EffectsDesigner.Partial/EffectsDesigner.Background.cs#L11

Proposed sol:
Detect the corrupted image object and remove it (?)

from log:
```
POWERPNT.EXE Error: 0 : 20170419110715: ApplyStyleInVariationStage: The specified file wasn't found. - System.ArgumentException:    at Microsoft.Office.Interop.PowerPoint.Shapes.AddPicture(String FileName, MsoTriState LinkToFile, MsoTriState SaveWithDocument, Single Left, Single Top, Single Width, Single Height)
   at PowerPointLabs.PictureSlidesLab.Service.EffectsDesigner.AddPicture(String imageFile, EffectName effectName)
   at PowerPointLabs.PictureSlidesLab.Service.EffectsDesigner.ApplyBackgroundEffect()
   at PowerPointLabs.PictureSlidesLab.Service.StylesDesigner.GenerateStyle(EffectsDesigner designer, ImageItem source, Boolean isActualSize)
   at PowerPointLabs.PictureSlidesLab.Service.StylesDesigner.ApplyStyle(ImageItem source, Slide contentSlide, Single slideWidth, Single slideHeight, StyleOption option)
   at PowerPointLabs.PictureSlidesLab.ViewModel.PictureSlidesLabWindowViewModel.ApplyStyleInVariationStage(Slide contentSlide, Single slideWidth, Single slideHeight)
```

**Comment by initialshl** [comment]
Hi, can I get more information on this? Is the image file corrupted on purpose, or it happens spontaneously?

**Comment by kai33** [comment]
The user didn't reply after this.
Two things that I currently suspect:
1. there may be a way to corrupt the files in PSL, if it's like this, we just need to detect and remove them. Or
2. PSL stores pictures into path `MyDocument` (code [link](https://github.com/PowerPointLabs/PowerPointLabs/blob/master/PowerPointLabs/PowerPointLabs/PictureSlidesLab/Util/StoragePath.cs#L18)), I wonder if the username contains special characters (french/latin/etc), does it break anything in things like file loading in PSL/pptlabs or picture loading in the office API?
We experienced similar things in the installer that, if the username contains special characters, ClickOnce installer then fails to work
