### ISSUE TITLE
Paste Lab: Exception when using replace with clipboard

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1354]
When I copy an image from desktop and use `Replace With Clipboard` on an item in a group, I get this exception:

![image](https://cloud.githubusercontent.com/assets/12381148/26289807/6f39f758-3ed5-11e7-9788-aada94421a7c.png)

It does not seem to happen with any other actions from paste lab.

Edit: Seems like the error triggers for all images, not just images from the desktop. I can trigger it by doing the following: Copy an image. Use `Replace With Clipboard` on a group. Undo. Use `Replace With Clipboard` on the same group. The error message should appear. Seems like 2016 does not have this bug

**Comment by IanTeo** [comment]
Stack trace:
System.Runtime.InteropServices.COMException
Exception from HRESULT: 0x800A01A8
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shape.get_GroupItems()
   at PowerPointLabs.PasteLab.ReplaceWithClipboard.Execute(PowerPointPresentation presentation, PowerPointSlide slide, Selection selection, ShapeRange pastingShapes) in C:\PowerPointLabs\PowerPointLabs\PowerPointLabs\PasteLab\ReplaceWithClipboard.cs:line 27
   at PowerPointLabs.ActionFramework.Action.PasteLab.ReplaceWithClipboardActionHandler.ExecutePasteAction(String ribbonId, PowerPointPresentation presentation, PowerPointSlide slide, Selection selection, ShapeRange pastingShapes) in C:\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Action\PasteLab\ReplaceWithClipboardActionHandler.cs:line 24
   at PowerPointLabs.ActionFramework.Action.PasteLab.PasteLabActionHandler.ExecuteAction(String ribbonId) in C:\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Action\PasteLab\PasteLabActionHandler.cs:line 47
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14

**Comment by IanTeo** [comment]
[Test.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/1017878/Test.pptx)
These are the slides I tested on
