### ISSUE TITLE
Paste Into Group has exception after undo

### ISSUE THREAD

**Issue by IanTeo** [PowerPointLabs/PowerPointLabs#1370]
Paste Into Group throws an uncaught exception if I paste, undo and paste again

**Comment by iskandarzulkarnaien** [comment]
System.Runtime.InteropServices.SEHException
External component has thrown an exception.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Effect.get_Shape()
   at PowerPointLabs.Models.PowerPointSlide.<>c__DisplayClass66_0.<TransferAnimation>b__1(Effect effect) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointSlide.cs:line 697
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PowerPointLabs.Models.PowerPointSlide.TransferAnimation(Shape source, Shape destination) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointSlide.cs:line 697
   at PowerPointLabs.PasteLab.PasteIntoGroup.Execute(PowerPointPresentation presentation, PowerPointSlide slide, ShapeRange selectedShapes, ShapeRange pastingShapes, Nullable`1 posLeft, Nullable`1 posTop, Shape shapeAbove) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\PasteLab\PasteIntoGroup.cs:line 19
   at PowerPointLabs.ActionFramework.PasteLab.PasteIntoGroupActionHandler.ExecutePasteAction(String ribbonId, PowerPointPresentation presentation, PowerPointSlide slide, ShapeRange selectedShapes, ShapeRange selectedChildShapes) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\PasteLab\PasteIntoGroup\PasteIntoGroupActionHandler.cs:line 40
   at PowerPointLabs.ActionFramework.PasteLab.PasteLabActionHandler.ExecuteAction(String ribbonId) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\PasteLab\PasteLabActionHandler.cs:line 89
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14
