### ISSUE TITLE
Opening Sync Lab causes exception

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1465]
From PPTLabs support group:
"When I try to open sync lab tab, it appears a warning message (the one that is written below) and don't allow me to open the tab."

```System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at PowerPointLabs.ActionFramework.Common.Extension.ActionFrameworkExtensions.RegisterTaskPane(Type taskPaneType, String taskPaneTitle, EventHandler visibleChangeEventHandler, EventHandler dockPositionChangeEventHandler)```

**Comment by alexfjw** [comment]
Looks like this happens for some versions of powerpoint.
I experienced with PPT2013 myself. It went away after trying another installer for PPT2013. 
My guess would be that the issue goes away after updating powerpoint. Perhaps we ask users to try that if the same thing happens again.

**Comment by alexfjw** [comment]
More updates:
I've tried to update PPT2013 to Office SP1 & installed updates to no avail. 
Another guess is that the issue comes from SyncLabShapeStorage's lazy init. That's where the exception led to upon further testing.

**Comment by alexfjw** [comment]
**Results of investigation**

It seems that we are unable to create a new powerpoint presentation using the given API. We do not encounter this problem on most MSO installations, giving us the intermittent problems.  
More specifically, `Presentations.Add(...)` throws an exception, when it shouldn't.
https://msdn.microsoft.com/en-us/library/microsoft.office.interop.powerpoint.presentations.add(v=office.14).aspx
I'm not sure how to dig deeper given that this is the only way to create a new presentation. Will be leaving this aside for now. 

ShapesLab does not work with this broken copy of MSO either. It tells me that the current ShapesLab directory does not work and I am unable to change the directory for saving shapes.

@junkiattan, @leeyh20 
Do share if you have any suggestions for workabouts.

**Comment by yuhongherald** [comment]
I get a null reference exception for PowerPointPresentation's Presentation.Slides.Count when opening SyncLab. Bug encountered on PPT 2013. To replicate:

Open a new presentation, then click on SyncLab.
