### ISSUE TITLE
Shapes Lab cannot be opened

### ISSUE THREAD

**Issue by initialshl** [PowerPointLabs/PowerPointLabs#1482]
A user posted his issue:
"I had a problem with the 2.8 version (shapes library did not load) and so I upgraded to versio 3.0. Now, when I click on the "Shapes Lab" Icon, I get the following error message (see below)."

```
System.ArgumentException
Illegal characters in path.
Stack Trace:
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at PowerPointLabs.ThisAddIn.InitializeShapesLabConfig()
   at PowerPointLabs.ActionFramework.Action.ShapesLabActionHandler.InitCustomShapePane()
   at PowerPointLabs.ActionFramework.Action.ShapesMenuActionHandler.ExecuteAction(String ribbonId)
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId)
```

ArgumentException on CreateDirectory (.NET) can be found here: https://msdn.microsoft.com/en-us/library/54a0at6s(v=vs.110).aspx

It is most probably because the user has invalid characters on his User directory path. 
Some solutions may be:
- Ask the user to type in a new path
- Default to a generic path (C:/PPTLabs)

**Comment by kai33** [comment]
This can be made into a framework for pptlabs,
like a generic layer for storage to
* store permanent states, and can migrate data to another folder (e.g. for shapes lab, picture slides lab)
* temp states & auto remove aft use (e.g. many features that will need temp image processing)
* each feature has their own folder structure (feature-level isolation)
* etc
