### ISSUE TITLE
ZoomLab: Error encounted when going through drill down tutorial

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1588]
```
System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  The specified data type is unavailable.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.PasteSpecial(PpPasteDataType DataType, MsoTriState DisplayAsIcon, String IconFileName, Int32 IconIndex, String IconLabel, MsoTriState Link)
   at PowerPointLabs.ZoomLab.AutoZoom.GetNextSlidePictureWithBackground(PowerPointSlide currentSlide, PowerPointSlide nextSlide)
   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded

Shapes (unknown member) : Invalid request.  The specified data type is unavailable.

System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  The specified data type is unavailable.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.PasteSpecial(PpPasteDataType DataType, MsoTriState DisplayAsIcon, String IconFileName, Int32 IconIndex, String IconLabel, MsoTriState Link)
   at PowerPointLabs.ZoomLab.AutoZoom.GetNextSlidePictureWithBackground(PowerPointSlide currentSlide, PowerPointSlide nextSlide)
   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded)
   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide)
   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation()
   at PowerPointLabs.ActionFramework.ZoomLab.DrillDownActionHandler.ExecuteAction(String ribbonId)
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId)
```

Error encountered by 2 users, with info as above.
One of them seems to be on office 365 (2016)

**Comment by junkiattan** [comment]
I think we need more context for this.
1. What version of PPT was being used?
2. What was the user doing when the error occurred?
3. Has the user successfully replicated the error? What are the use cases that created the error?

With this, we can get a clearer picture of which part of the code produces the error

**Comment by alexfjw** [comment]
User didn't reply when I asked for more info. Guess that's all we have for now.

**Comment by yuhongherald** [comment]
#1915 introduces a fix for this.
