### ISSUE TITLE
Error while opening pptx file

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1608]
I have a pptx file that gives this error. I've been using that file for many years. Error started after I modified the file today using PowerPointLabs.
The file still opens and is usable though.
```
Application (unknown member) : Invalid request.  There is no currently active document window.

System.Runtime.InteropServices.COMException
Application (unknown member) : Invalid request.  There is no currently active document window.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint._Application.get_ActiveWindow()
   at PowerPointLabs.Models.PowerPointCurrentPresentationInfo.get_CurrentSelection()
   at PowerPointLabs.ActionFramework.Common.Extension.ActionFrameworkExtensions.GetCurrentSelection()
   at PowerPointLabs.ActionFramework.Common.Extension.BaseHandlerExtensions.GetCurrentSelection(BaseHandler handler)
   at PowerPointLabs.ActionFramework.AnimationLab.DrillDownEnabledHandler.GetEnabled(String ribbonId)
   at PowerPointLabs.ActionFramework.Common.Interface.EnabledHandler.Get(String ribbonId)
```

**Comment by damithc** [comment]
Env: Win 10, PPT 2013

**Comment by Skaty** [comment]
- What kind of modifications were made to the file?
- PPTLabs version?

**Comment by damithc** [comment]
> What kind of modifications were made to the file?
> PPTLabs version?

I don't think it's related to the modification. I get the error even when I open blank pptx files. Looks like some meta data expected by PowerPointLabs is corrupted. There was a 'PowerPoint auto-saved a file; do you want to keep it?' message when I opened PPT today. The file name had SyncLab or ShapesLab in it, but I deleted it without thinking too much. Probably that's what caused the problem. 

Latest public release.

**Comment by leeyh20** [comment]
Seems similar to #1543, but I thought it was only for empty ppts. I'll try investigating this.

**Comment by alexfjw** [comment]
I also encountered a similar problem recently when creating new powerpoints. A blank powerpoint's fine but selecting one of those preset templates seems to give the same error on 2016. 
`Invalid request.  There is no currently active document window.` 
I'll check that out again in a bit.

**Comment by damithc** [comment]
I can open the same file in my other comp without an error. However, I noticed these warnings. Looks like something went wrong with our meta-data files 

![image](https://user-images.githubusercontent.com/1673303/36294524-3eaf6e1c-131c-11e8-9afc-1c54dc56f444.png)

**Comment by leeyh20** [comment]
I have investigated the above issue regarding the meta-data files, I believe its caused by #1432. Thus the powerpoints are not closed properly.

**Comment by ChesterSng** [comment]
@leeyh20 can we close this issue?
