### ISSUE TITLE
Error "there is no currently active document window" when there is no presentation open

### ISSUE THREAD

**Issue by leeyh20** [PowerPointLabs/PowerPointLabs#1615]
Steps to reproduce bug:

1. Click File --> Close for any presentation.
2. Go to PowerPointLabs tab
3. Wait a while or click ShapesLab, EffectsLab. PositionsLab etc.
4. There will be various COMException thrown for "there is no currently active document window".
```
System.Runtime.InteropServices.COMException
Application (unknown member) : Invalid request.  There is no currently active document window.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint._Application.get_ActiveWindow()
   at PowerPointLabs.ActionFramework.Common.Extension.ActionFrameworkExtensions.RegisterTaskPane(Type taskPaneType, String taskPaneTitle, EventHandler visibleChangeEventHandler, EventHandler dockPositionChangeEventHandler) in D:\Git Projects\PPLABS\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Extension\ActionFrameworkExtensions.cs:line 99
```

**Comment by leeyh20** [comment]
@initialshl @IanTeo Sorry, could I ask if there is a way to disable / grey out all the menu buttons on the PPT Ribbon? Can menu buttons like "AnimationLabMenu" and "ZoomLabMenu" use an enabled handler?

**Comment by initialshl** [comment]
@leeyh20 We couldnt find a way to do that in the past
