### ISSUE TITLE
Clipboard is Empty or Contains Data which may not be pasted (AgendaLab)

### ISSUE THREAD

**Issue by alexfjw** [PowerPointLabs/PowerPointLabs#1658]
```System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.Paste()  
   at PowerPointLabs.Utils.ShapeUtil.SyncWholeShape(Shape refShape, Shape& candidateShape, PowerPointSlide candidateSlide)  
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncShapesFromReferenceSlide(PowerPointSlide refSlide, PowerPointSlide candidate, List'1 markedForDeletion)  
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide refSlide, List'1 sections, AgendaSection currentSection, List'1 deletedShapeNames, PowerPointSlide targetSlide)  
   at PowerPointLabs.AgendaLab.AgendaLabMain.<>c.<.cctor>b__120_0(PowerPointSlide refSlide, List'1 sections, AgendaSection currentSection, List'1 deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide targetSlide)   
  at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate template, TemplateIndexTable templateTable,  
```

```
System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.Paste()
   at PowerPointLabs.Utils.ShapeUtil.SyncWholeShape(Shape refShape, Shape& candidateShape, PowerPointSlide candidateSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncShapesFromReferenceSlide(PowerPointSlide refSlide, PowerPointSlide candidate, List'1 markedForDeletion)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide refSlide, List'1 sections, AgendaSection currentSection, List'1 deletedShapeNames, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.<>c.<.cctor>b__120_0(PowerPointSlide refSlide, List'1 sections, AgendaSection currentSection, List'1 deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate template, TemplateIndexTable templateTable, PowerPointSlide refSlide, List'1 sections, List'1 deletedShapeNames, AgendaSection currentSection)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker slideTracker, PowerPointSlide refSlide, Func'1 generateTemplate)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlides(SlideSelectionTracker slideTracker, PowerPointSlide refSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.CreateBulletAgenda(SlideSelectionTracker slideTracker)
   at PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type)
   at PowerPointLabs.ActionFramework.AgendaLab.TextAgendaActionHandler.ExecuteAction(String ribbonId)
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId)
```

**Comment by yuhongherald** [comment]
#1915 fixes the same issue
