### ISSUE TITLE
Error when using 'zoom to area'

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1769]
v4.4.0.0 Dev
PPT 2016 Win10

Steps:
* Use zoom-to-area in the attached slide.
[zoomLaberror.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/2840603/zoomLaberror.pptx)

>System.Runtime.InteropServices.COMExceptionShapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.Stack Trace:   at Microsoft.Office.Interop.PowerPoint.Shapes.Paste()   at PowerPointLabs.ZoomLab.ZoomToArea.GetBestFitShape(PowerPointSlide currentSlide, Shape zoomShape)   at PowerPointLabs.ZoomLab.ZoomToArea.<>c__DisplayClass3_0.<GetEditedShapesForZoomToArea>b__0(Shape zoomShape)   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   at PowerPointLabs.ZoomLab.ZoomToArea.GetEditedShapesForZoomToArea(PowerPointSlide currentSlide, List`1 zoomRectangles)   at PowerPointLabs.ZoomLab.ZoomToArea.AddZoomToArea()

**Comment by damithc** [comment]
@blewjy can look into this?

**Comment by blewjy** [comment]
Sure, I'll investigate this

**Comment by blewjy** [comment]
Prof @damithc, I am unable to reproduce this error on PPT2016 and PPT2013, Win10.

However, I did notice that there are some hidden shapes on the slide that have animations as well - were those hidden shapes placed there manually or was it caused by some other earlier ZoomLab operations?

**PPT2016**
1. Go to Home Ribbon, under the Editing group, click Select and open the Selection Pane
2. You should see a bunch of shapes named 'PPTLabsMagnifyShapes...' that are hidden.

Although I was unable to reproduce this error, I would think that it was probably caused by those hidden shapes. It would be more useful if we can find out what caused those shapes to be there in the first place.

**Comment by leeyh20** [comment]
I have seen bug reports being filed that are similar to this error before, but I never managed to reproduce this error. I have been wondering if the clipboard happens to be locked at a certain point of time or the hidden shapes failed to be copied to the clipboard ?

**Comment by damithc** [comment]
I could not reproduce in my home comp (PPT 2013, Win 10). 
The hidden shapes were generated by the `zoom to area` feature itself, when I tried it earlier. The feature fails after generating half the animations.
The problem is unlikely to be due to hidden shapes because the failure happened even when I tried on example given in the Tutorial file which came with the fresh install.

**Comment by ChesterSng** [comment]
> System.Runtime.InteropServices.COMExceptionShapes (unknown member) : Invalid request. Clipboard is empty or contains data which may not be pasted here.Stack Trace: at Microsoft.Office.Interop.PowerPoint.Shapes.Paste() at PowerPointLabs.ZoomLab.ZoomToArea.GetBestFitShape(PowerPointSlide currentSlide, Shape zoomShape) at PowerPointLabs.ZoomLab.ZoomToArea.<>c__DisplayClass3_0.b__0(Shape zoomShape) at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at PowerPointLabs.ZoomLab.ZoomToArea.GetEditedShapesForZoomToArea(PowerPointSlide currentSlide, List`1 zoomRectangles) at PowerPointLabs.ZoomLab.ZoomToArea.AddZoomToArea()

I get the same error message using other labs that involve clipboard as well. Running functional tests (AgendaLab, ShapesLab and more) sometimes will result in the same error message thrown.

**Comment by damithc** [comment]
I continue to get the error in my office comp. Here's the result after trying the feature on a fresh pptx file. Note how some animations have been created. I get the error dialog twice. Is there any log I can send?
[zoomLaberror2.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/2850860/zoomLaberror2.pptx)

**Comment by leeyh20** [comment]
#920 details the same problem too

**Comment by ChesterSng** [comment]
> Steps:
* Use zoom-to-area in the attached slide.
  [zoomLaberror.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/2840603/zoomLaberror.pptx)

Using this pptx I got a different exception: 
`PowerPointLabs.CropLab.CropLabException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at PowerPointLabs.CropLab.CropToShape.Crop(PowerPointSlide currentSlide, ShapeRange shapeRange, Double magnifyRatio, Boolean isInPlace, Boolean handleError) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\CropLab\CropToShape.cs:line 79
   at PowerPointLabs.CropLab.CropToShape.Crop(PowerPointSlide currentSlide, Selection selection, Double magnifyRatio, Boolean isInPlace, Boolean handleError) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\CropLab\CropToShape.cs:line 34
   at PowerPointLabs.Models.PowerPointMagnifyingSlide.AddZoomSlideCroppedPicture(Single magnifyRatio) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointMagnifyingSlide.cs:line 148
   at PowerPointLabs.Models.PowerPointMagnifyingSlide.PrepareForZoomToArea(Shape zoomShape) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointMagnifyingSlide.cs:line 75
   at PowerPointLabs.Models.PowerPointMagnifyingSlide.AddZoomToAreaAnimation(Shape zoomShape) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointMagnifyingSlide.cs:line 38
   at PowerPointLabs.ZoomLab.ZoomToArea.AddMultiSlideZoomToArea(PowerPointSlide currentSlide, List`1 shapesToZoom) in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\ZoomToArea.cs:line 74
   at PowerPointLabs.ZoomLab.ZoomToArea.AddZoomToArea() in C:\Users\Chester\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\ZoomToArea.cs:line 37`

**Comment by damithc** [comment]
Seems to be fixed in 4.8.0.0 (Dev-release) 👍
