### ISSUE TITLE
Shapes Lab storage error

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1886]
## Bug Report 
Shapes Lab will never start correctly if there is a category that cannot be retrieved. There is no option to reset shapes lab to mediate the problem either.
![image](https://user-images.githubusercontent.com/40821389/56137193-d8faf700-5fc6-11e9-8545-67fed93005ef.png)

#### Environment
PowerPoint 2016

#### Steps to replicate
Have a category with an illegal name, (eg. `COM1`). Currently error is given whenever shapes lab is open.

#### Recommended fix
Delete the category that cause the problem.

#### Other info (Stack Trace)
System.IO.DirectoryNotFoundException
Could not find a part of the path 'C:\'.
Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheckCategorySlideToLocal(PowerPointSlide category) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 390
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.InitCategories() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 571
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheck() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 317
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.Open(Boolean readOnly, Boolean untitled, Boolean withWindow, Boolean focus) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 237
   at PowerPointLabs.ThisAddIn.InitializeShapeGallery() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ThisAddIn.cs:line 179
   at PowerPointLabs.ShapesLab.Views.CustomShapePaneWPF.SetStorageSettings() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ShapesLab\Views\CustomShapePaneWPF.xaml.cs:line 95
   at PowerPointLabs.ShapesLab.CustomShapePane.InitCustomShapePaneStorage() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ShapesLab\CustomShapePane.Designer.cs:line 57
   at PowerPointLabs.ActionFramework.ShapesLab.ShapesLabActionHandler.ExecuteAction(String ribbonId) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ActionFramework\ShapesLab\ShapesLabActionHandler.cs:line 28
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14

**Comment by YuPeiHenry** [comment]
Turns out this was caused by having a category with name `COM1`, which was filtered in a recent PR (but this category got created before that).
