### ISSUE TITLE
Error in Zoom Lab: Step Back

### ISSUE THREAD

**Issue by YuPeiHenry** [PowerPointLabs/PowerPointLabs#1913]
Sent by a user. Error details:

```
System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shapes.Paste()
   at PowerPointLabs.ZoomLab.AutoZoom.GetStepBackWithBackgroundShapeToZoom(PowerPointSlide currentSlide, PowerPointSlide addedSlide, Shape previousSlidePicture, Shape& backgroundShape)
   at PowerPointLabs.ZoomLab.AutoZoom.AddStepBackAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointStepBackSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded)
```

**Comment by yuhongherald** [comment]
I got another error when using ZoomLab.

To reproduce:
1. Open powerpoint.
2. Create new presentation.
3. On the first slide, add e-Learning Lab with callout, caption and Voice.
4. Create a new slide after the first slide.
5. Add a rectangle.
6. Now use ZoomLab's step back. The error occurs here.

This is how it looks after the error:
![image](https://user-images.githubusercontent.com/28508438/58227332-fa38cb00-7d5c-11e9-86a2-6be89c8cc8eb.png)

Error details:
System.UnauthorizedAccessException
Grouping is disabled for the selected shapes.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.ShapeRange.Group()
   at PowerPointLabs.Models.PowerPointDeMagnifyingSlide.GetShapeToZoomWithBackground(Shape zoomShape) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointDeMagnifyingSlide.cs:line 151
   at PowerPointLabs.Models.PowerPointDeMagnifyingSlide.AddZoomToAreaAnimation(Shape zoomShape) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointDeMagnifyingSlide.cs:line 82
   at PowerPointLabs.ZoomLab.ZoomToArea.AddMultiSlideZoomToArea(PowerPointSlide currentSlide, List`1 shapesToZoom) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\ZoomToArea.cs:line 91
   at PowerPointLabs.ZoomLab.ZoomToArea.AddZoomToArea() in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\ZoomToArea.cs:line 37

**Comment by yuhongherald** [comment]
I got another error.

Open powerpoint.
Add a rectangle.
Create a new slide.
Add another rectangle.
Use ZoomLab's step back. Error occurs here.

System.UnauthorizedAccessException
Grouping is disabled for the selected shapes.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.ShapeRange.Group()
   at PowerPointLabs.ZoomLab.AutoZoom.GetStepBackWithoutBackgroundShapeToZoom(PowerPointSlide addedSlide, PowerPointSlide previousSlide) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\AutoZoom.cs:line 434
   at PowerPointLabs.ZoomLab.AutoZoom.AddStepBackAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointStepBackSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\AutoZoom.cs:line 176

**Comment by damithc** [comment]
In the attached slide, the zoom to area features work for only one of the rectangles:
![image](https://user-images.githubusercontent.com/1673303/58235333-30814500-7d73-11e9-9d8a-22d7c6906d9f.png)

![image](https://user-images.githubusercontent.com/1673303/58235406-53135e00-7d73-11e9-90ff-6b3e83e0314a.png)

[zoom to area error.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/3210891/zoom.to.area.error.pptx)

**Comment by yuhongherald** [comment]
PPT 2016, Win10

The following error occured when I tried to apply Drill Down from Zoom Lab, with background turned off.

System.Runtime.InteropServices.COMException
Shape (unknown member) : Invalid request.  To select a shape, its view must be active.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Shape.Select(MsoTriState Replace)
   at PowerPointLabs.ZoomLab.AutoZoom.SelectAllShape(List`1 shapes) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\AutoZoom.cs:line 431
   at PowerPointLabs.ZoomLab.AutoZoom.GetNextSlidePictureWithoutBackground(PowerPointSlide currentSlide, PowerPointSlide nextSlide, Shape& pictureOnNextSlide) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\AutoZoom.cs:line 276
   at PowerPointLabs.ZoomLab.AutoZoom.AddDrillDownAnimation(Shape selectedShape, PowerPointSlide currentSlide, PowerPointDrillDownSlide& addedSlide, Boolean includeAckSlide, Boolean deletePreviouslyAdded) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\ZoomLab\AutoZoom.cs:line 80

**Comment by yuhongherald** [comment]
> PPT2016, Win10
> 
> In the attached slide, the zoom to area features work for only one of the rectangles:
> ![image](https://user-images.githubusercontent.com/1673303/58235333-30814500-7d73-11e9-9d8a-22d7c6906d9f.png)
> 
> ![image](https://user-images.githubusercontent.com/1673303/58235406-53135e00-7d73-11e9-90ff-6b3e83e0314a.png)
> 
> [zoom to area error.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/3210891/zoom.to.area.error.pptx)

I experience the same problem with rounded rectangles that have the their rounded corners removed.

![image](https://user-images.githubusercontent.com/28508438/58302889-fc179280-7e1f-11e9-8cb1-5ccfdcb2f2aa.png)
![image](https://user-images.githubusercontent.com/28508438/58302944-3bde7a00-7e20-11e9-94b4-5d5191308eda.png)

**Comment by yuhongherald** [comment]
Another user encountered a clipboard error when creating text agenda. Error details:
Powerpoint Office365Plus

OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)).


System.Runtime.InteropServices.COMExceptionOpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))Stack Trace:   at Microsoft.Office.Core.TextRange2.Copy()   at PowerPointLabs.Utils.ShapeUtil.SyncTextRange(TextRange2 refTextRange, TextRange2 candidateTextRange, Boolean pickupTextContent, Boolean pickupTextFormat)   at PowerPointLabs.AgendaLab.AgendaLabMain.ApplyBulletFormats(TextRange2 textRange, BulletFormats bulletFormats, AgendaSection currentSection)   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide refSlide, List`1 sections, AgendaSection currentSection, List`1 deletedShapeNames, PowerPointSlide targetSlide)   at PowerPointLabs.AgendaLab.AgendaLabMain.<>c.<.cctor>b__120_1(PowerPointSlide refSlide, List`1 sections, AgendaSection currentSection, List`1 deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide targetSlide)   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate template, TemplateIndexTable templateTable, PowerPointSlide refSlide, List`1 sections, List`1 deletedShapeNames, AgendaSection currentSection)   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker slideTracker, PowerPointSlide refSlide, Func`1 generateTemplate)   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlides(SlideSelectionTracker slideTracker, PowerPointSlide refSlide)   at PowerPointLabs.AgendaLab.AgendaLabMain.CreateBulletAgenda(SlideSelectionTracker slideTracker)   at PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type)   at PowerPointLabs.ActionFramework.AgendaLab.TextAgendaActionHandler.ExecuteAction(String ribbonId)   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId)
```

**Comment by yuhongherald** [comment]
related issues:
Clipboard: #1599, #1658, #1624, #920
Others: #1588

**Comment by yuhongherald** [comment]
For the Step Back button greying out, I experienced the same problem, but I can't reliably reporduce the error:
1. Step back
2. Undo
3. Try to step back the same shape. The button should be greyed out.

**Comment by damithc** [comment]
Any chance of fixing this issue?
