### ISSUE TITLE
Error in NarrationsLab: Record Audio Manually Multiple Slide Sections index out of range.

### ISSUE THREAD

**Issue by yuhongherald** [PowerPointLabs/PowerPointLabs#1917]
![image](https://user-images.githubusercontent.com/28508438/58463936-5ccc0580-8167-11e9-8e03-f94f6892174d.png)

PPT 2016, Win 10
To replicate:
1. Open new ppt presentation.
2. Create a new section named "Untitled Section".
3. Create a new slide.
4. Create another new section named "Untitled Section", containing the new slide.
5. Open recorder pane by going to Narrations > Record Audio Manually.
6. Press Record During Slide Show on the recorder pane.
7. A slide show should have started. Start and stop recording, twice. On the second time, the error dialog should appear.

Error log:
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PowerPointLabs.ELearningLab.Views.RecorderTaskPane.GetRecordIndexFromScriptIndex(Int32 relativeId, Int32 scriptIndex) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\NarrationsLab\Views\RecorderTaskPane.cs:line 338
   at PowerPointLabs.ELearningLab.Views.RecorderTaskPane.GetPlaybackFromList(Int32 scriptIndex, Int32 slideId) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\NarrationsLab\Views\RecorderTaskPane.cs:line 391
   at PowerPointLabs.ELearningLab.Views.RecorderTaskPane.StopButtonRecordingHandler(Int32 scriptIndex, PowerPointSlide currentSlide, Boolean buffered) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\NarrationsLab\Views\RecorderTaskPane.cs:line 1211
   at PowerPointLabs.ELearningLab.Views.InShowRecordingControl.RecButton_Click(Object sender, RoutedEventArgs e) in C:\Users\Herald\Documents\PowerPointLabs\PowerPointLabs\PowerPointLabs\NarrationsLab\Views\InShowRecordingControl.xaml.cs:line 126
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by yuhongherald** [comment]
Closing issue as we are planning to retire NarrationsLab in favor of eLearningLab.
