### ISSUE TITLE
Error when opening ShapesLab

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#1930]
v5.1.0.0 (dev release)

I get this error when opening the shapes lab:
>System.IO.IOException
Cannot create a file when that file already exists.
Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.RetrievePptxFile()
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.Open(Boolean readOnly, Boolean untitled, Boolean withWindow, Boolean focus)
   at PowerPointLabs.ThisAddIn.InitializeShapeGallery()
   at PowerPointLabs.ShapesLab.Views.CustomShapePaneWPF.SetStorageSettings()
   at PowerPointLabs.ShapesLab.CustomShapePane.InitCustomShapePaneStorage()
   at PowerPointLabs.ActionFramework.ShapesLab.ShapesLabActionHandler.ExecuteAction(String ribbonId)
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId)

**Comment by damithc** [comment]
Due to this error, I cannot load my previous shapes.

**Comment by YuPeiHenry** [comment]
It seems that the line responsible for this is 
`650: File.Move(shapeGalleryFileName, FullName);`
getting placed before the check:
`653: if (File.Exists(FullName))`.

I will shift the lines tonight. @damithc For urgent fixes such as this, does it get merged in the next dev-release? (since its not a public release)

**Comment by damithc** [comment]
> I will shift the lines tonight. @damithc For urgent fixes such as this, does it only get updated in the next dev-release? (since its not a public release)

yes, good enough if fixed before the next public release.
