### ISSUE TITLE
Replace with clipboard feature deletes custom movement animation path

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [PowerPointLabs/PowerPointLabs#2012]
Paste Lab's `replace with clipboard` feature is stated in the user guide to preserve the target (i.e. replaced) object's animations. However, custom drawn movement paths are destroyed.

**Comment by iskandarzulkarnaien** [comment]
Seems like undo-ing the action after the path is destroyed causes the animation to be duplicated.

Attempting to replace again causes the following exception to be thrown:

```
External component has thrown an exception.

Help us fix the problem by emailing pptlabs@comp.nus.edu.sg.

System.Runtime.InteropServices.SEHException
External component has thrown an exception.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Effect.get_Shape()
   at PowerPointLabs.Models.PowerPointSlide.DeleteShapeAnimations(Shape sh) in C:\Users\user\Downloads\NUS\CS32812\PPL\PowerPointLabs\PowerPointLabs\Models\PowerPointSlide.cs:line 723
   at PowerPointLabs.PasteLab.ReplaceWithClipboard.Execute(PowerPointPresentation presentation, PowerPointSlide slide, ShapeRange selectedShapes, ShapeRange selectedChildShapes, ShapeRange pastingShapes) in C:\Users\user\Downloads\NUS\CS32812\PPL\PowerPointLabs\PowerPointLabs\PasteLab\ReplaceWithClipboard.cs:line 33
   at PowerPointLabs.ActionFramework.PasteLab.ReplaceWithClipboardActionHandler.ExecutePasteAction(String ribbonId, PowerPointPresentation presentation, PowerPointSlide slide, ShapeRange selectedShapes, ShapeRange selectedChildShapes) in C:\Users\user\Downloads\NUS\CS32812\PPL\PowerPointLabs\PowerPointLabs\ActionFramework\PasteLab\ReplaceWithClipboard\ReplaceWithClipboardActionHandler.cs:line 34
   at PowerPointLabs.ActionFramework.PasteLab.PasteLabActionHandler.ExecuteAction(String ribbonId) in C:\Users\user\Downloads\NUS\CS32812\PPL\PowerPointLabs\PowerPointLabs\ActionFramework\PasteLab\PasteLabActionHandler.cs:line 89
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\Users\user\Downloads\NUS\CS32812\PPL\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14
```

**Comment by iskandarzulkarnaien** [comment]
Additionally, it seems ReplaceWithClipboard only preserves the earliest 2 animations applied.
