### ISSUE TITLE
ShapeLab: Library import fails if clipboard is empty

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [PowerPointLabs/PowerPointLabs#2014]
Importing a library in ShapeLab fails if the clipboard is empty.

**Comment by iskandarzulkarnaien** [comment]
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.

System.Runtime.InteropServices.COMException
Shapes (unknown member) : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
Stack Trace:
   at PowerPointLabs.ActionFramework.Common.Extension.PPLClipboard.LockAndRelease[TResult](Func`1 action) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Extension\PPLClipboard.cs:line 90
   at PowerPointLabs.ActionFramework.Common.Extension.PPLClipboard.LockAndRelease(Action action) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Extension\PPLClipboard.cs:line 74
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheckCategoryLocalToSlide() in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 416
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.InitCategories() in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 651
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheck() in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 361
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.Open(Boolean readOnly, Boolean untitled, Boolean withWindow, Boolean focus) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 277
   at PowerPointLabs.ShapesLab.Views.CustomShapePaneWPF.ImportShapes(String importFilePath, Boolean fromLibrary) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ShapesLab\Views\CustomShapePaneWPF.xaml.cs:line 715

**Comment by iskandarzulkarnaien** [comment]
Add Spotlight Exception

```System.Runtime.InteropServices.COMException
Selection (unknown member) : Invalid request.  Nothing appropriate is currently selected.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint.Selection.get_ShapeRange()
   at PowerPointLabs.EffectsLab.Spotlight.AddSpotlightEffect() in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\EffectsLab\Spotlight.cs:line 44
   at PowerPointLabs.ActionFramework.EffectsLab.AddSpotlightActionHandler.<>c.<ExecuteAction>b__0_0() in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\EffectsLab\Spotlight\AddSpotlight\AddSpotlightActionHandler.cs:line 28
   at PowerPointLabs.Utils.ClipboardUtil.RestoreClipboardAfterAction[TResult](Func`1 action, PowerPointPresentation pres, PowerPointSlide origSlide) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\Utils\ClipboardUtil.cs:line 83
   at PowerPointLabs.ActionFramework.EffectsLab.AddSpotlightActionHandler.ExecuteAction(String ribbonId) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\EffectsLab\Spotlight\AddSpotlight\AddSpotlightActionHandler.cs:line 26
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\Users\user\Desktop\Code\PowerPointLabs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14
```

**Comment by iskandarzulkarnaien** [comment]
Seems like this issue also occurs if the clipboard has items that cannot be saved or pasted (e.g. a folder)

**Comment by ccyccyccy** [comment]
Is there anyway to reproduce these bugs?

**Comment by iskandarzulkarnaien** [comment]
The behavior appears to be inconsistent. Attempting to import a shapelab library on an empty clipboard seems to be the most consistent in throwing exception.

**Comment by ccyccyccy** [comment]
> Add Spotlight Exception

This only happens for me when I have items in the clipboard. The exception does not occur when my clipboard is empty. Is it the same for you? @iskandarzulkarnaien

**Comment by iskandarzulkarnaien** [comment]
>
> This only happens for me when I have items in the clipboard. The exception does not occur when my clipboard is empty. Is it the same for you? @iskandarzulkarnaien

I reproduced the problem by doing the following:

1. Clear clipboard by entering the following into command prompt: `cmd /c "echo off|clip"`
2. Attempt to Add Spotlight, Exception Thrown

For me, no exception is thrown if my clipboard has anything in it.
