### ISSUE TITLE
Ensure compatibility with PPT 2016

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/powerpointlabs#796]
More and more users are asking for this.

**Comment by damithc** [comment]
One user reported some features are not working for 2016 e.g. zoom to area

**Comment by kai33** [comment]
One user reported this stacktrace:
System.NullReferenceException
Object reference not set to an instance of an object.
Stack Trace:
   at PowerPointLabs.Utils.Graphics.SetText(Shape shape, IEnumerable`1 lines)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide
refSlide, List`1 sections, AgendaSection currentSection, List`1
deletedShapeNames, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.<.cctor>b__4e(PowerPointSlide
refSlide, List`1 sections, AgendaSection currentSection, List`1
deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide
targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate
template, TemplateIndexTable templateTable, PowerPointSlide refSlide,
List`1 sections, List`1 deletedShapeNames, AgendaSection
currentSection)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker
slideTracker, PowerPointSlide refSlide, Func`1 generateTemplate)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlides(SlideSelectionTracker
slideTracker, PowerPointSlide refSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type)
   at PowerPointLabs.Ribbon1.BulletPointAgendaClick(IRibbonControl control)

**Comment by kai33** [comment]
I simply tested pptlabs in Win10 Office2016 (Office365),
looks like no compatibility issue for Office2016, and all features are working fine.

**Comment by kai33** [comment]
A public release has been made to fix bugs in Auto Animate/Animate in Slide/Zoom to Area on Oct 31 which may have resolved the not-working problems

**Comment by damithc** [comment]
We need to update the website about 2016 compatibility.
