### ISSUE TITLE
NullReferenceException in AgendaLab

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/PowerPointLabs#823]
Received this from a user:
I've just tried out your software, and I must say it's a excellent idea to supercharge PowerPoint presentations. I created a Text Agenda and switched it to Visual and reverted back to Text. Worked fine. Then Modified the Agenda Template. Noticed that even though I removed the background graphics from it, it didn't remove itself from the slides on choosing Sync Agenda.

Later when I removed the agenda and re-added it I got the error below. The newly created agenda slides apart from the first look blank, and no matter how many times I removed the Agenda it seems to be giving the same resutls.

System.NullReferenceException
Object reference not set to an instance of an object.
Stack Trace:
   at PowerPointLabs.Utils.Graphics.SetText(Shape shape, IEnumerable`1 lines)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide refSlide, List`1 sections, AgendaSection currentSection, List`1 deletedShapeNames, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.<.cctor>b__4e(PowerPointSlide refSlide, List`1 sections, AgendaSection currentSection, List`1 deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate template, TemplateIndexTable templateTable, PowerPointSlide refSlide, List`1 sections, List`1 deletedShapeNames, AgendaSection currentSection)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker slideTracker, PowerPointSlide refSlide, Func`1 generateTemplate)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlides(SlideSelectionTracker slideTracker, PowerPointSlide refSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type)
   at PowerPointLabs.Ribbon1.BulletPointAgendaClick(IRibbonControl control)

**Comment by kai33** [comment]
Similar case:

One user reported this stacktrace:
> I was operating the tutorial and was in the middle of generating a text agenda when the error occurred.
System.NullReferenceException
Object reference not set to an instance of an object.
Stack Trace:
   at PowerPointLabs.Utils.Graphics.SetText(Shape shape, IEnumerable`1 lines)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlide(PowerPointSlide
refSlide, List`1 sections, AgendaSection currentSection, List`1
deletedShapeNames, PowerPointSlide targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.<.cctor>b__4e(PowerPointSlide
refSlide, List`1 sections, AgendaSection currentSection, List`1
deletedShapeNames, Boolean isNewlyGenerated, PowerPointSlide
targetSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseAllSlides(AgendaTemplate
template, TemplateIndexTable templateTable, PowerPointSlide refSlide,
List`1 sections, List`1 deletedShapeNames, AgendaSection
currentSection)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SynchroniseSlidesUsingTemplate(SlideSelectionTracker
slideTracker, PowerPointSlide refSlide, Func`1 generateTemplate)
   at PowerPointLabs.AgendaLab.AgendaLabMain.SyncBulletAgendaSlides(SlideSelectionTracker
slideTracker, PowerPointSlide refSlide)
   at PowerPointLabs.AgendaLab.AgendaLabMain.GenerateAgenda(Type type)
   at PowerPointLabs.Ribbon1.BulletPointAgendaClick(IRibbonControl control)

**Comment by damithc** [comment]
This one was reported on Dec 1st. Office 2010 32 Bit version, on a 64 Bit Windows 7 OS

**Comment by Ohohcakester** [comment]
I can't seem to reproduce this bug.
Note: the backgrounds not syncing is expected behaviour. Only single-colour backgrounds sync.

From the stack trace, the bug appears to occur when a new text agenda is generated. (not on a synchronise). However, no matter how I generate the text agenda (both on my own slides and on the tutorial), it always works properly.
Tried text agenda -> visual agenda -> text agenda -> remove agenda -> text agenda -> remove agenda -> text agenda -> etc etc etc
Even experimented with things like changing the default slide layout to blank. Still no problem. No problem syncing either, even after modifying the reference slide, adding backgrounds, and deleting random things from the other agenda slides.

I also use Office 2010 32 Bit, on a 64 Bit Windows 7 OS.

From what I can see in the stack trace, this is what happens:
 1. User clicks Generate Text Agenda
 2. Reference slide is generated
 3. Blank slides are created for each section (to be filled in later)
 4. Agenda Lab syncs Reference slide to first agenda slide.
   * a Shapes in reference slide are copied over to first agenda slide
   * b. Agenda Lab can't locate the "content" shape (which holds the bullet points) is located in the first agenda slide, setting it to null. (Even though it should be there because of step a)
   * c. Agenda Lab tries to set the text of the null "content" shape, which causes an exception.
 5. The rest of the slides remain blank as the procedure has terminated early.

**Comment by kai33** [comment]
Can ask the user to send us the buggy slides?

**Comment by damithc** [comment]
I've asked. Waiting for his reply.

**Comment by damithc** [comment]
File sent it email.

**Comment by damithc** [comment]
@Ohohcakester can have a look at this one?

**Comment by Ohohcakester** [comment]
I looked through it a few days back with the file you sent. No matter what I tried, I couldn't get an exception or any similar unexpected behaviour to occur.

**Comment by damithc** [comment]
Yes, it is not reproducible because the steps to reproduce must be very unique. Perhaps just analyze the stack trace and see if we can deduce how the exception could possibly be thrown? If the cause cannot be deduced, may be treat the symptom? Note that when this happens Agenda lab stops working until PowerPoint is restarted. One user claims he had to restart the computer to get it working again.

**Comment by damithc** [comment]
Closing as this is an old issue
