### ISSUE TITLE
Auto Animation exception: another slide already has this name

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/PowerPointLabs#836]
a user reported this:
System.Runtime.InteropServices.COMException
Slide (unknown member) : Invalid request.  Another slide already has this name.
Stack Trace:
   at Microsoft.Office.Interop.PowerPoint._Slide.set_Name(String Name)
   at PowerPointLabs.AutoAnimate.PrepareNextSlide(PowerPointSlide nextSlide)
   at PowerPointLabs.AutoAnimate.AddCompleteAnimations(PowerPointSlide currentSlide, PowerPointSlide nextSlide)
   at PowerPointLabs.AutoAnimate.AddAutoAnimation()

**Comment by kai33** [comment]
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/AutoAnimate.cs#L144
https://github.com/PowerPointLabs/powerpointlabs/blob/master/PowerPointLabs/PowerPointLabs/AutoAnimate.cs#L146

should also use GUID to make the slide name more unique
